[WIP] Django Rest-Frameworkとカスタムユーザーモデルの実装
IkaProduction/RefreshList_server pull request #22
Opened 2019-12-16 14:14 UTC by suzuki84g

## 概要

まず前提として、アプリ単位にfutureを2つに切るべきでした。
PRが複雑化してしまうことを身を以て理解したので、以降是正します。
関連するIssueはClose出来ないので、一旦DraftでPRします。

- Django Rest-Framework（以下DRF）の実装 #13 
    - DRFの実装に伴う関連コードの改修
- カスタムユーザーモデルの精緻化 #11 #12 
- その他、pep8に則った不要な記述の削除

## 使い方

初回起動はREADME.md参照。
前回のPRから`user.User` を丸ごと作り変えているので、`migrate`でエラーが出るかもしれません。

- http://127.0.0.1:8000/admin
所謂Djangoのadminです。

- http://127.0.0.1:8000/api
DRFで実装されるAPIコンソール。GUI操作でGETもPOSTもできる。
詳細はこれから実装します。概要は以下のQiitaが読みやすい。
https://qiita.com/kimihiro_n/items/86e0a9e619720e57ecd8

- http://127.0.0.1:8000/
urlsやviewの連結を勉強する為に、Defaultから変えました。いつものです。

## Request/Responseの主な変更点

- `/api/todos`
実装されました。
何もかもが出来てしまうので、制限をかけていく必要があります。

- `/api/users`
`/api`には表示されていますが、エラーが出ます。
これは、DRFを実装したあとにカスタムユーザーモデルを実装した為です。
今後改修します。

## 技術的変更点概要

- DRFの動作（詳細は前述のQiitaをご参照下さい）
    - `serializer.py` modelを定義する
    - `viewset.py' 操作する処理を書く
    - `urls.py` routerを定義して連結

- カスタムユーザーモデル
    - `Class UserManager`がユーザー作成を担当
    - `Class User`がユーザー情報を定義

## DB変更点

使い方に記載済みですが、DB:ikalistの`users_user`がまるごと置き換わっている為、マイグレーションが必要です。
使用するユーザーもrootからikachanに変えました。
変えたからDB再構築必須でした。

## テスト結果とテスト項目

* [ ] DBを初期化して`python manage.py makemigrations`が行える。
* [ ] `python manage.py migrate`にエラーが発生しない。
* [ ] `python manage.py runserver`を実施し、`http://127.0.0.1:8000/`以下にアクセス出来る。
* [ ] `python manage.py createsuperuser`が実行出来る。
* [ ] 作成したユーザーでadminページからログイン
* [ ] `/api/todo`でTodoの登録が行えること

## 今回保留した項目とTODOリスト

- `/api/users`から一般ユーザーの登録を実装（現状adminページからは出来る）
- ログイン及びログアウトの実装
- ログインしているユーザーのtodoのみを表示させる

ここまで出来れば、標準的なdjangoのユーザー管理とDRFは機能的には（私が）使えるようになっている、と思うので、他のissueはある程度スムーズに実装出来る、はず。

以上、宜しくお願い致します。

2019-12-16 14:22 UTC, suzuki84g commented
クソ長いPRは、訊きたかった事を書いてる途中に忘れるから本当にクソ。
以下、意見下さい。

## DRFと機能（アプリ）の切り方について

DRFの処理ですが、`/ikatodo/urls.py`から`/todolist/urls.py`を参照させて、`/todolist/viewset.py`に繋いでいます。
これは、usersとtodos、両方同じです。
ユーザー関連のAPI処理は`/ikatodo/urls.py`から、`/users/urls.py`に飛ばすべきでしょうか。

2019-12-17 08:14 UTC, otera05 requested changes
遅くなりましたがコメントしましたー
コメントした箇所を修正したり、不要なファイルを削除して再度プッシュしてみてください。

2019-12-17 08:14 UTC, otera05 commented on todo_post.py
> +)
ファイルにメソッドの定義何もないのちょっと笑いましたｗ

```python
def create_user()
```

みたいなメソッド作ってその中に処理書いていきましょう。

2019-12-17 08:14 UTC, otera05 commented on ikatodo/urls.py
> +    path('', include('todolist.urls')),
これは多分 `templates/todolist/todo_list.html` を描画させるためのURLマッピングですね。
動作確認用に追加してるのであれば残しておいてもいいですが、今回は不要なので消してもいいかなと思います。

というのも、25行目で include してる引数と字面が似てるので混乱するし削除したいなーと思いました。

2019-12-17 08:14 UTC, otera05 commented on users/forms.py
> +        return self.initial["password"]
Django Rest Framework 使うなら forms.py は不要ですね。
forms.py は Django 上で入力フォームをレンダリングする時に使うファイルで、今回の Django の立ち位置は API サーバなので form は不要です。
form (フロント)から送られてくるユーザ情報やTodoの情報を受け取れれば後は Django Rest Framework で Post 処理させればOKのはずです。

2019-12-17 09:55 UTC, otera05 commented
>DRFの処理ですが、/ikatodo/urls.pyから/todolist/urls.pyを参照させて、/todolist/viewset.pyに繋いでいます。
これは、usersとtodos、両方同じです。
ユーザー関連のAPI処理は/ikatodo/urls.pyから、/users/urls.pyに飛ばすべきでしょうか。

これ完全に見えてなかったです。
URLのマッピングは機能毎に分けるべきだと考えます。
DRF で実装したことがないので具体的なコードはちょっとすぐには分かんないけど。

2019-12-17 13:28 UTC, suzuki84g commented on todo_post.py
> +)
消したつもりだったのに残ってしまっていました…。本当に恥ずかしい…。
pullするときにはゴミが残っていないか確認してからやるようにします、申し訳ない。

2019-12-17 14:54 UTC, otera05 commented
forms.py は削除してないみたいですけど削除し忘れ？

2019-12-17 14:58 UTC, suzuki84g commented
forms.py消してadmin.pyも弄ってたらadminサイト止まったので影響範囲確認してます。

2019-12-17 15:13 UTC, suzuki84g commented on users/forms.py
> +        return self.initial["password"]
`forms.py`を消すと`admin.py`でエラーが出て、`admin.py`を初期値に戻しても解消しないのでちょっと困っています。

2019-12-17 15:24 UTC, suzuki84g commented on users/forms.py
> +        return self.initial["password"]
`admin.py`の修正範囲を絞ったら無事動きました。良かった。

2019-12-18 01:35 UTC, otera05 commented on todo_post.py
> +)
pull じゃなくて push ねｗ

2019-12-18 10:37 UTC, suzuki84g commented on ikatodo/urls.py
> +    path('', include('todolist.urls')),
rootにアクセスされた時に何か表示されてた方が良いと思っていましたが、フロント側の実装をやる時に実装するなりリダイレクトさせるなりするべきですね。
何れにしても現状不要なので削除しました。

2019-12-18 10:40 UTC, suzuki84g commented
> > DRFの処理ですが、/ikatodo/urls.pyから/todolist/urls.pyを参照させて、/todolist/viewset.pyに繋いでいます。
> > これは、usersとtodos、両方同じです。
> > ユーザー関連のAPI処理は/ikatodo/urls.pyから、/users/urls.pyに飛ばすべきでしょうか。
> 
> これ完全に見えてなかったです。
> URLのマッピングは機能毎に分けるべきだと考えます。
> DRF で実装したことがないので具体的なコードはちょっとすぐには分かんないけど。

#24 で対応しますが、APIでの操作を丸ごと、アプリ`api`に切り出すことにします。

@otera05 
change request貰った箇所は一通り修正してpushしました、再度reviewお願いします。

2019-12-18 15:40 UTC, otera05 approved these changes
このブランチでローカルでちゃんと動作してるならOKです！ 👍

2019-12-18 15:40 UTC, otera05 commented on users/admin.py
> +    # HACK(suzuki): form.pyに関連する項目のみ削除したら動いた（丸ごと消したらerrorになる）ので取り急ぎ動かす用。
- forms.py -> 削除したファイル
- 全削除 -> error になる
- forms.py に関連する項目のみ削除 -> ちゃんと動く

ということなので、ちゃんと依存性を理解した上で追加・削除できるようになりましょう。
最初はコピペで作っていくのはもちろんいいと思いますが、「なぜここに書くのか、なぜこう書くのか、コピペしたこのコードの意味するところは何か」ということを常に意識していきましょう。

2019-12-18 21:07 UTC, merged